- docs/source/plugins.md
- docs/source/plugins/cfd.md
- docs/source/plugins/lca.md
- docs/source/plugins/overview.md
- docs/source/plugins/teaser.md
Some more docs for the plugins
> further docs for plugins

- .gitlab-ci.yml
- README.md
merge together with https://github.com/BIM2SIM/bim2sim/pull/466
> Hotfix teaser regression

- .gitlab-ci.yml
- README.md
- docs/requirements.txt
apply hotfix for sphinx.
This also brings 2 other hotfix from main into development.
> Hotifx sphinx doc

- .gitlab-ci.yml
- README.md
- docs/requirements.txt
Currently dev shows 3 commits behind even if the commits are already merged in dev. This should hopefully solve this.
> merge main in dev

- bim2sim/kernel/ifc2python.py
- bim2sim/plugins/PluginEnergyPlus/bim2sim_energyplus/__init__.py
- bim2sim/task/bps/check_ifc.py
- bim2sim/task/common/common.py
Make sure that files with invalid IFC schema lead to program abort.
> 170 integrate common tasks for validation

- .gitlab-ci.yml
this solves the issue with new dockerhubs limits
> use locker docker, and dind images

- bim2sim/decision/__init__.py
- bim2sim/decision/console.py
- bim2sim/kernel/attribute.py
- bim2sim/plugins/PluginAixLib/test/integration_test/test_hvac.py
- bim2sim/task/common/common.py
- bim2sim/task/hvac/dead_ends.py
With this, the additional information regarding an element for decisions will be handled by a new attribute `console_identifier` which is only used in console frontend. Goal is primary a more clean visualization of decisions in the webtool frontend.
> 508 improve decisions handover to webtool

- bim2sim/plugins/PluginEnergyPlus/bim2sim_energyplus/task/ep_idf_postprocessing.py
fixes current problem with df.append() depracted which makes EP tests fail
> use concat as pandas depcrated the usage of df.append()

- bim2sim/kernel/hvac/assets/plotting/pyvis_options.json
- bim2sim/kernel/hvac/hvac_graph.py
- bim2sim/plugins/PluginAixLib/requirements.txt
- bim2sim/plugins/PluginHKESim/requirements.txt
- bim2sim/plugins/PluginTEASER/requirements.txt
- bim2sim/task/hvac/hvac.py
> use pyvis to create interactive plots and store in export folder

- bim2sim/plugins/PluginEnergyPlus/bim2sim_energyplus/task/ep_create_idf.py
- bim2sim/sim_settings.py
- bim2sim/tasks/bps/enrich_material.py
- test/unit/test_sim_settings.py
This solved some of the problems discussed in #556 but not everything. The usage of enums still have to be done and the communication between config.toml file and settings must also be improved.
> 556 settings

- bim2sim/plugins/PluginTEASER/bim2sim_teaser/__init__.py
- bim2sim/plugins/PluginTEASER/bim2sim_teaser/task/__init__.py
- bim2sim/plugins/PluginTEASER/bim2sim_teaser/task/create_teaser_prj.py
- bim2sim/plugins/PluginTEASER/bim2sim_teaser/task/export_teaser.py
This splits the previous task export into two tasks:
- model creation 
- export
> split model creation and export for TEASER

- bim2sim/elements/bps_elements.py
- bim2sim/elements/mapping/units.py
- bim2sim/plugins/PluginEnergyPlus/bim2sim_energyplus/task/ep_idf_postprocessing.py
- bim2sim/tasks/bps/verify.py
fixes bug with enrichment with LOD.full because `total_thickness` doesn't exist but is named `thickness`
> fix enrichment for layersets

- bim2sim/elements/base_elements.py
- bim2sim/plugins/PluginLCA/bim2sim_lca/__init__.py
- bim2sim/plugins/PluginLCA/bim2sim_lca/examples/e1_export_quantities_for_lca.py
- bim2sim/plugins/PluginLCA/test/integration/test_lca.py
- bim2sim/sim_settings.py
- bim2sim/tasks/bps/enrich_material.py
This adds enrichment possibility for LCA analysis as well. Therefore we needed to add the new Materials created through enrichment to `instances` and change the `default_tasks` for LCAPlugin. I added some warnings and error messages while dealing with enrichment.
Still some work to make enrichment process more straight forward and better understandable.
> Hotfix lca enriched materials

- bim2sim/plugins/PluginEnergyPlus/test/integration/test_energyplus.py
- bim2sim/plugins/PluginEnergyPlus/test/regression/test_energyplus.py
- bim2sim/plugins/PluginTEASER/test/integration/test_teaser.py
- bim2sim/tasks/common/create_elements.py
- bim2sim/tasks/common/load_ifc.py
- bim2sim/utilities/common_functions.py
- requirements.txt
this is needed as string_grouper package leeds to errors with install now and is not activly maintained anymore. See [here](https://github.com/Bergvca/string_grouper/issues/93)
> remove string_grouper and replace by own function

- bim2sim/tasks/bps/enrich_use_cond.py
- bim2sim/utilities/common_functions.py
Clarify the parameter names in enrich_use_cond.py to clearly distinguish zone-usage definitions (mapping table) and use conditions per zone.
> rename custom use conditions and usage mapping

- bim2sim/plugins/PluginEnergyPlus/test/integration/test_energyplus.py
- bim2sim/plugins/PluginEnergyPlus/test/regression/test_energyplus.py
needed update due to renaming to `energyplus-regressions`
> use new energyplus_regressions instead epregression imports

- README.md
- docs/source/user-guide/PluginTemplate.md
minor correction of the documentation
> Docu update

- bim2sim/elements/base_elements.py
- bim2sim/elements/mapping/attribute.py
> remove doubled function get_exact_association

- bim2sim/assets/enrichment/usage/commonUsages.json
- bim2sim/elements/mapping/finder.py
- bim2sim/plugins/PluginEnergyPlus/bim2sim_energyplus/task/ep_create_idf.py
- bim2sim/tasks/bps/enrich_use_cond.py
- bim2sim/tasks/common/load_ifc.py
- bim2sim/utilities/common_functions.py
Changes:
* wildcard functionality for easier identification of usages of thermal zones
* a few new common usages
* make sure that decision global keys are unique for decision of source tools if multiple not defined source tools exist (might happen for models manipulated and exported again by simpleBIM)
> 591 large bps models

- bim2sim/plugins/PluginEnergyPlus/bim2sim_energyplus/task/ep_create_idf.py
related to #622, we forgot to remove a #TODO
> update inline comment

- bim2sim/plugins/PluginTEASER/bim2sim_teaser/__init__.py
- bim2sim/tasks/common/__init__.py
- bim2sim/tasks/common/deserialize_elements.py
- bim2sim/tasks/common/serialize_elements.py
> add tasks for serialization and deserialization

- bim2sim/elements/bps_elements.py
starting to solve problems with roof/groundfloors by improving top_bottom function
> fix top_bottom for SBs without relating bound

- bim2sim/plugins/PluginEnergyPlus/bim2sim_energyplus/__init__.py
- bim2sim/plugins/PluginEnergyPlus/bim2sim_energyplus/task/__init__.py
- bim2sim/plugins/PluginEnergyPlus/bim2sim_energyplus/task/ep_add_2b_bounds.py
- bim2sim/plugins/PluginTEASER/bim2sim_teaser/__init__.py
- bim2sim/sim_settings.py
- bim2sim/tasks/bps/__init__.py
- bim2sim/tasks/bps/sb_2b_generation.py
- bim2sim/tasks/bps/sb_correction.py
- bim2sim/tasks/bps/sb_creation.py
Move space boundary correction and space boundary 2b generation (for closing gaps) to BPS tasks. Add simsettings with defaults.
> 642 move sb corrections to createspaceboundary task

- test/unit/elements/aggregation/test_pipestrand.py
- test/unit/elements/aggregation/test_underfloorheating.py
Remove write to local `c:/temp` directory.
> remove graph.plot(r'c:\temp') call in tests

- bim2sim/plugins/PluginTEASER/bim2sim_teaser/task/create_teaser_prj.py
this fixes the current CI which crashs due to an update in TEASER
> adapt to new TEASER version with different dataclass handling

- bim2sim/sim_settings.py
- bim2sim/tasks/hvac/connect_elements.py
> add sim_setting for connect element tolerance

- bim2sim/tasks/bps/enrich_material.py
- bim2sim/tasks/bps/enrich_use_cond.py
> add information where enrichment data is coming from.

- bim2sim/plugins/PluginComfort/bim2sim_comfort/task/plot_comfort_results.py
- bim2sim/tasks/bps/plot_results.py
Updates on colormap and comfort
> 715 improve energyplus result plotting

- bim2sim/plugins/PluginComfort/bim2sim_comfort/task/create_result_df.py
- bim2sim/tasks/bps/plot_results.py
fix comfort results, remove absolute results. Improve y-limits for plotting
> fix comfort result plots 

- bim2sim/elements/bps_elements.py
- bim2sim/elements/mapping/attribute.py
- bim2sim/plugins/PluginTEASER/bim2sim_teaser/models/__init__.py
- test/unit/elements/mapping/test_attribute.py
> add attr_type to use decisions also for non real values

- bim2sim/plugins/PluginEnergyPlus/bim2sim_energyplus/task/create_result_df.py
- bim2sim/plugins/PluginEnergyPlus/bim2sim_energyplus/task/ep_create_idf.py
> Fix heating energy outputs for rooms

- .gitlab-ci.yml
Fix that not all tests for all plugins are executed.
> Hotfix ci integration tests

- docs/source/developer-guide/contribute.md
Add description for version guidelines
> Update contribute.md with versioning guidelines

- bim2sim/examples/e1_template_plugin.py
- bim2sim/examples/e2_interactive_project.py
- bim2sim/kernel/log.py
- bim2sim/plugins/PluginAixLib/bim2sim_aixlib/examples/e1_simple_project_hvac_aixlib.py
- bim2sim/plugins/PluginAixLib/bim2sim_aixlib/examples/e2_complex_project_hvac_aixlib.py
- bim2sim/plugins/PluginComfort/bim2sim_comfort/examples/e1_simple_project_comfort_energyplus.py
- bim2sim/plugins/PluginComfort/bim2sim_comfort/examples/e3_load_comfort_simulation_results.py
- bim2sim/plugins/PluginEnergyPlus/bim2sim_energyplus/examples/e1_simple_project_energyplus.py
- bim2sim/plugins/PluginEnergyPlus/bim2sim_energyplus/examples/e2_complex_project_energyplus.py
- bim2sim/plugins/PluginEnergyPlus/bim2sim_energyplus/examples/e3_load_energyplus_simulation_results.py
- bim2sim/plugins/PluginHKESim/bim2sim_hkesim/examples/e1_simple_project_hvac_hkesim.py
- bim2sim/plugins/PluginHKESim/test/integration/test_hkesim.py
- bim2sim/plugins/PluginLCA/bim2sim_lca/examples/e1_export_quantities_for_lca.py
- bim2sim/plugins/PluginTEASER/bim2sim_teaser/examples/e1_simple_project_bps_teaser.py
- bim2sim/plugins/PluginTEASER/bim2sim_teaser/examples/e2_complex_project_teaser.py
- bim2sim/plugins/PluginTEASER/bim2sim_teaser/examples/e3_load_teaser_simulation_results.py
- bim2sim/plugins/PluginTEASER/bim2sim_teaser/examples/e4_visualize_zone_binding.py
- bim2sim/project.py
- docs/source/user-guide/PluginTemplate.md
- pyproject.toml
> move default_loggin_setup() call into base project log setup

- .gitmodules
- pyproject.toml
we merged #741 too early, this finalizes the update.
> 740 update to new teaser use conditions

- bim2sim/kernel/log.py
- bim2sim/plugins/PluginComfort/bim2sim_comfort/examples/e3_load_comfort_simulation_results.py
- bim2sim/plugins/PluginEnergyPlus/bim2sim_energyplus/examples/e1_simple_project_energyplus.py
- bim2sim/plugins/PluginEnergyPlus/bim2sim_energyplus/examples/e2_complex_project_energyplus.py
- bim2sim/plugins/PluginEnergyPlus/bim2sim_energyplus/examples/e3_load_energyplus_simulation_results.py
- bim2sim/plugins/PluginHKESim/bim2sim_hkesim/examples/e1_simple_project_hvac_hkesim.py
- bim2sim/plugins/PluginHKESim/test/integration/test_hkesim.py
- bim2sim/plugins/PluginLCA/bim2sim_lca/examples/e1_export_quantities_for_lca.py
- bim2sim/plugins/PluginTEASER/bim2sim_teaser/examples/e1_simple_project_bps_teaser.py
- bim2sim/plugins/PluginTEASER/bim2sim_teaser/examples/e2_complex_project_teaser.py
- bim2sim/plugins/PluginTEASER/bim2sim_teaser/examples/e3_load_teaser_simulation_results.py
- bim2sim/plugins/PluginTEASER/bim2sim_teaser/examples/e4_visualize_zone_binding.py
- bim2sim/plugins/PluginTEASER/bim2sim_teaser/examples/e5_serialize_teaser_prj.py
- bim2sim/project.py
Currently, there are issues that logging handlers are not deleted correctly. This will solve this and also cleanup the logging infrastructure a bit to make it easier to understand.
> Fix logging

- bim2sim/plugins/PluginEnergyPlus/bim2sim_energyplus/task/ep_create_idf.py
this solves a bug where adiabatic surfaces might still have fenestration objects, as previously we iterated over the list that we were changing during the iteration. (Concurrent Modification problem)
> this makes sure that all fenestration objects are removed from adiabatic surfaes.

- bim2sim/plugins/PluginTEASER/bim2sim_teaser/task/create_teaser_prj.py
closes #786 (see issue description for further information)
> set year of construction to 2000 for min_admissible_elements to incease robustness

- pyproject.toml
Fix energyplus regressions version
> Fix energyplus regressions version

- bim2sim/project.py
This makes sure that the global key for interactive project decisions is unique
> make global key unique for interactive task decision

- bim2sim/elements/base_elements.py
- bim2sim/elements/mapping/filter.py
- bim2sim/plugins/PluginAixLib/bim2sim_aixlib/examples/e1_simple_project_hvac_aixlib.py
- bim2sim/sim_settings.py
- bim2sim/tasks/common/create_elements.py
closes #692 and includes further improvements in element creation process
> 692 sequence of decisions stays not the same
